# Generated by Django 5.1.15 on 2026-07-23 05:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publisher", "0002_initial"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(help_text='Reporting month, "YYYY-MM".', max_length=7),
                ),
                (
                    "html",
                    models.TextField(help_text="Rendered, self-contained white-label report."),
                ),
                ("total_posts", models.PositiveIntegerField(default=0)),
                ("total_platform_posts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "publisher_workspace_report",
                "ordering": ["-period"],
                "indexes": [models.Index(fields=["workspace", "-period"], name="idx_wsreport_ws_period")],
                "unique_together": {("workspace", "period")},
            },
        ),
    ]
