# Generated by Django 5.1.15 on 2026-07-16 18:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0015_per_account_status"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label for this token, e.g. 'ACC theshortcutsai'.",
                        max_length=100,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_tokens",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "api_ingest_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        db_index=True,
                        help_text="Sibling-supplied idempotency key, e.g. 'acc:post-31-...:en'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_records",
                        to="composer.post",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_records",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingest_records",
                        to="api.ingesttoken",
                    ),
                ),
            ],
            options={
                "db_table": "api_ingest_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
